[package]
name = "AutoKillah"
version = "0.1.0"
authors = ["bulengerkacper <bulenger.kacper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.28"
nalgebra = "0.23"